import Head from "next/head";
import Image from "next/image";
import { AiOutlineUsergroupAdd } from "react-icons/ai";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Form from "@/components/Form";
import Table from "@/components/Table";

export default function Home() {
    const [visible, setVisible] = useState(false);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="text-center text-2xl font-medium">
                    Employee Management
                </h1>
                <div className="container mx-auto">
                    <button
                        onClick={() => setVisible(!visible)}
                        className="flex items-center gap-3 bg-indigo-400 py-2 px-4 rounded-sm mt-4 mb-4"
                    >
                        Add Employee <AiOutlineUsergroupAdd />
                    </button>
                    {visible ? <Form /> : <></>}
                    <hr />
                    <Table />
                </div>
            </main>
        </>
    );
}
